# Generated by Django 3.0.5 on 2020-05-09 07:20
import random

from django.db import migrations


class Migration(migrations.Migration):

    def forward(apps, schema_editor):
        Group = apps.get_model('student', 'Group')
        Student = apps.get_model('student', 'Student')
        group_ids = [group.id for group in Group.objects.all().only('id')]
        for student in Student.objects.all().only('id', 'group'): #.iterator():
            student.group = random.choice(list(Group.objects.all().only('id')))
            # student.group_id = random.choice(group_ids)
            student.save(update_fields=['group'])

    def backward(apps, schema_editor):
        Student = apps.get_model('student', 'Student')
        for student in Student.objects.all().only('id', 'group'): #.iterator():
            student.group = None
            student.save(update_fields=['group'])

    dependencies = [
        ('student', '0003_auto_20200509_0719'),
    ]

    operations = [
        migrations.RunPython(
            code=forward,
            reverse_code=backward
        ),
    ]
