# Generated by Django 3.0.5 on 2020-05-09 09:02

from django.db import migrations

def forward(app, db_schema):
    query = """
            select t1.id, t1.email
    from  student_student as t1
    inner join
          (
              select id, email, count(*) as num_of_emails
              from student_student
              group by email
              having num_of_emails > 1
          ) as t0
    on t0.email=t1.email
    order by  t1.email
    """

    # Student = app.get_model('student', 'Student')
    # qs = Student.objects.raw(query)
    #
    # curr_email, idx = '', 0
    # for entry in qs:
    #     if entry.email != curr_email:
    #         curr_email = entry.email
    #         idx = 0
    #     else:
    #         entry.email += f'_duplicated_{idx}'
    #         entry.save()
    #         idx += 1


def backward(app, db_schema):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200509_0932'),
    ]

    operations = [
        migrations.RunPython(
            code=forward,
            reverse_code=backward
        )
    ]



